"""empty message

Revision ID: 2f4f28850ce0
Revises: e4ba1540de42
Create Date: 2025-11-19 13:13:25.485852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4f28850ce0'
down_revision = 'e4ba1540de42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_starships_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planets_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'starships', ['starships_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_planets_id_fkey', 'characters', ['planets_id'], ['id'])
        batch_op.create_foreign_key('favorites_starships_id_fkey', 'characters', ['starships_id'], ['id'])

    # ### end Alembic commands ###
